name: absensi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  camera: ^0.10.5+9
  connectivity: ^3.0.6
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  fluentui_system_icons: ^1.1.236
  flutter:
    sdk: flutter
  flutter_lightbox: ^0.1.3
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png