// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQxPQTSmHoFOrGrlNANz-QTRALg9mk_Nk',
    appId: '1:973133608527:web:5492963dfaac9d12',
    messagingSenderId: '973133608527',
    projectId: 'rafael-nuansa',
    authDomain: 'rafael-nuansa.firebaseapp.com',
    databaseURL: 'https://rafael-nuansa.firebaseio.com',
    storageBucket: 'rafael-nuansa.appspot.com',
    measurementId: 'G-20LPN7WHW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlRoy7wNJ42yZwmbeefTxrAAl5PZdghic',
    appId: '1:973133608527:android:708d9543b5a9af65d95c3a',
    messagingSenderId: '973133608527',
    projectId: 'rafael-nuansa',
    databaseURL: 'https://rafael-nuansa.firebaseio.com',
    storageBucket: 'rafael-nuansa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaGRbzp_G3uVOk2g6EHTRwlj1xUZJrQHI',
    appId: '1:973133608527:ios:73b2d57a38341e34d95c3a',
    messagingSenderId: '973133608527',
    projectId: 'rafael-nuansa',
    databaseURL: 'https://rafael-nuansa.firebaseio.com',
    storageBucket: 'rafael-nuansa.appspot.com',
    iosClientId: '973133608527-gju5969ktbrohvlaldr5nee0o6llts8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaGRbzp_G3uVOk2g6EHTRwlj1xUZJrQHI',
    appId: '1:973133608527:ios:73b2d57a38341e34d95c3a',
    messagingSenderId: '973133608527',
    projectId: 'rafael-nuansa',
    databaseURL: 'https://rafael-nuansa.firebaseio.com',
    storageBucket: 'rafael-nuansa.appspot.com',
    iosClientId: '973133608527-gju5969ktbrohvlaldr5nee0o6llts8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQxPQTSmHoFOrGrlNANz-QTRALg9mk_Nk',
    appId: '1:973133608527:web:5c4c0734516c5dc9d95c3a',
    messagingSenderId: '973133608527',
    projectId: 'rafael-nuansa',
    authDomain: 'rafael-nuansa.firebaseapp.com',
    databaseURL: 'https://rafael-nuansa.firebaseio.com',
    storageBucket: 'rafael-nuansa.appspot.com',
    measurementId: 'G-SHJK7MNXYS',
  );
}
